# Generated by Django 4.2.9 on 2026-06-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='message_permission',
            field=models.CharField(choices=[('open', 'Anyone can message me'), ('request_required', 'Contact request required')], default='open', max_length=20),
        ),
    ]
