# Generated by Django 4.2.9 on 2026-06-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_font_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='onboarding_complete',
            field=models.BooleanField(default=False),
        ),
    ]
