# Generated by Django 4.2.9 on 2026-06-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_onboarding_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_internal_access',
            field=models.BooleanField(default=False),
        ),
    ]
