from django.urls import path
from .api_views import (
    InternalRoleListView,
    InternalRoleDetailView,
    DepartmentListView,
    DepartmentDetailView,
    DepartmentStatsView,
    OrgMemberListView,
    OrgMemberDetailView,
    OrgMembersExportView,
    MemberProfileView,
    OrgMeView,
    OrgUserSearchView,
    OrgNotificationListView,
    OrgNotificationDetailView,
    OnboardingTemplateListView,
    OnboardingTemplateDetailView,
    OnboardingTemplateCloneView,
    OnboardingTemplateImportView,
    TaskTemplateItemListView,
    TaskTemplateItemDetailView,
    OnboardingInstanceListView,
    OnboardingInstanceDetailView,
    OnboardingResetView,
    OnboardingRemindView,
    TaskInstanceDetailView,
    TaskInstanceListView,
    TaskCommentListView,
    MyOnboardingView,
    OnboardingStatsView,
    TemplateFormFieldListView,
    TemplateFormFieldDetailView,
    TaskFormFieldListView,
    TaskFormFieldDetailView,
    TaskFormSubmitView,
    # Phase 4
    DocumentTemplateListView,
    DocumentTemplateDetailView,
    DocumentTemplateAssignView,
    DocumentTemplateImportView,
    AllDocumentsAdminView,
    DocumentGlobalStatsView,
    DocumentExportView,
    DocumentReviewView,
    MyDocumentsView,
    MyDocumentUploadView,
    MyDocumentSignView,
    DocumentRemindView,
    DocumentDeleteView,
    CourseListView,
    CourseDetailView,
    CourseModuleListView,
    CourseModuleDetailView,
    ModuleLessonListView,
    ModuleLessonDetailView,
    LessonFileUploadView,
    DuplicateLessonView,
    ReorderLessonsView,
    CourseEnrollView,
    CourseEnrollmentListView,
    CourseUnenrollView,
    MyTrainingView,
    LessonCompleteView,
    QuizQuestionListView,
    QuizQuestionDetailView,
    LessonSubmitView,
    # Phase 5
    EventListView,
    EventDetailView,
    EventRSVPView,
    EventAttendanceAdminView,
    EventTypeConfigListView,
    EventTypeConfigDetailView,
    EventSettingsView,
    ContributionListView,
    ContributionSummaryView,
    ContributionInsightsView,
    ContributionMembersView,
    ContributionBulkReviewView,
    ContributionDetailView,
    ContributionReviewView,
    ContributionAdminSummaryView,
    ContributionOverviewView,
    ContributionByDepartmentView,
    ContributionExportView,
    CheckInListView,
    CheckInDetailView,
    CheckInReviewView,
    # Phase 6
    AdminDashboardView,
    ResourceListView,
    ResourceDetailView,
    AuditLogListView,
    OrgSettingsView,
    AnalyticsView,
    MemberPerformanceView,
    RecruitmentListView,
    RecruitmentReviewView,
    # Phase 9
    MemberStatsView,
    AccessRequestListView,
    AccessRequestReviewView,
    # Member Fingerprint
    MemberTrainingView,
    # Standalone Forms
    StandaloneFormListView,
    StandaloneFormDetailView,
    StandaloneFormFieldListView,
    StandaloneFormFieldDetailView,
    FormDistributeView,
    FormSubmitView,
    FormResponsesView,
    MyFormsView,
    FormInsightsView,
    ExtensionRequestSubmitView,
    ExtensionRequestListView,
    ExtensionRequestReviewView,
    # Org Chat
    OrgChannelListView,
    OrgChannelDetailView,
    OrgChannelMembersView,
    OrgChannelMessageListView,
    OrgChannelMessageDetailView,
    OrgChannelMessagePinView,
    OrgChannelMessageReactView,
    OrgDMConversationListView,
    OrgDMMessageListView,
    OrgDMMessageDetailView,
    OrgChannelPollListView,
    OrgChannelPollDetailView,
    OrgChannelPollVoteView,
)

urlpatterns = [
    # Roles
    path('org/roles/',                                      InternalRoleListView.as_view()),
    path('org/roles/<int:pk>/',                             InternalRoleDetailView.as_view()),
    # Departments — stats before <int:pk> to avoid conflict
    path('org/departments/stats/',                            DepartmentStatsView.as_view()),
    path('org/departments/',                                DepartmentListView.as_view()),
    path('org/departments/<int:pk>/',                       DepartmentDetailView.as_view()),
    # Members — stats before <int:pk> to avoid conflict
    path('org/members/stats/',                             MemberStatsView.as_view()),
    path('org/members/export/',                            OrgMembersExportView.as_view()),
    path('org/members/',                                   OrgMemberListView.as_view()),
    path('org/members/<int:pk>/',                          OrgMemberDetailView.as_view()),
    path('org/members/<int:pk>/profile/',                  MemberProfileView.as_view()),
    path('org/members/<int:pk>/training/',                 MemberTrainingView.as_view()),
    # Current user
    path('org/me/',                                        OrgMeView.as_view()),
    path('org/search-users/',                              OrgUserSearchView.as_view()),
    # Access Requests
    path('org/access-requests/',                           AccessRequestListView.as_view()),
    path('org/access-requests/<int:pk>/review/',           AccessRequestReviewView.as_view()),
    # Notifications
    path('org/notifications/',                              OrgNotificationListView.as_view()),
    path('org/notifications/<int:pk>/',                     OrgNotificationDetailView.as_view()),
    # Onboarding Templates
    path('org/templates/',                                  OnboardingTemplateListView.as_view()),
    path('org/templates/import/',                           OnboardingTemplateImportView.as_view()),
    path('org/templates/<int:pk>/',                         OnboardingTemplateDetailView.as_view()),
    path('org/templates/<int:pk>/clone/',                   OnboardingTemplateCloneView.as_view()),
    path('org/templates/<int:pk>/tasks/',                   TaskTemplateItemListView.as_view()),
    path('org/template-tasks/<int:pk>/',                    TaskTemplateItemDetailView.as_view()),
    # Onboarding Instances — stats/my before <pk> to avoid conflict
    path('org/onboardings/stats/',                          OnboardingStatsView.as_view()),
    path('org/my-onboarding/',                              MyOnboardingView.as_view()),
    path('org/onboardings/',                                OnboardingInstanceListView.as_view()),
    path('org/onboardings/<int:pk>/',                       OnboardingInstanceDetailView.as_view()),
    path('org/onboardings/<int:pk>/reset/',                 OnboardingResetView.as_view()),
    path('org/onboardings/<int:pk>/remind/',                OnboardingRemindView.as_view()),
    path('org/onboardings/<int:onboarding_pk>/tasks/',                          TaskInstanceListView.as_view()),
    path('org/onboardings/<int:onboarding_pk>/tasks/<int:task_pk>/', TaskInstanceDetailView.as_view()),
    path('org/onboardings/<int:onboarding_pk>/tasks/<int:task_pk>/comments/', TaskCommentListView.as_view()),
    path('org/onboardings/<int:onboarding_pk>/tasks/<int:task_pk>/form-fields/', TaskFormFieldListView.as_view()),
    path('org/onboardings/<int:onboarding_pk>/tasks/<int:task_pk>/submit-form/', TaskFormSubmitView.as_view()),
    path('org/task-form-fields/<int:pk>/',                         TaskFormFieldDetailView.as_view()),
    path('org/template-tasks/<int:task_pk>/form-fields/',          TemplateFormFieldListView.as_view()),
    path('org/template-form-fields/<int:pk>/',                     TemplateFormFieldDetailView.as_view()),
    # Document Templates (admin)
    path('org/doc-templates/import/',              DocumentTemplateImportView.as_view()),
    path('org/doc-templates/',                              DocumentTemplateListView.as_view()),
    path('org/doc-templates/<int:pk>/',                     DocumentTemplateDetailView.as_view()),
    path('org/doc-templates/<int:pk>/assign/',              DocumentTemplateAssignView.as_view()),
    # All Documents (admin) — fixed paths before <int:pk>
    path('org/documents/global-stats/',                    DocumentGlobalStatsView.as_view()),
    path('org/documents/export/',                          DocumentExportView.as_view()),
    path('org/documents/',                                  AllDocumentsAdminView.as_view()),
    path('org/documents/<int:pk>/review/',                  DocumentReviewView.as_view()),
    path('org/documents/<int:pk>/remind/',                  DocumentRemindView.as_view()),
    path('org/documents/<int:pk>/delete/',                  DocumentDeleteView.as_view()),
    # My Documents (member)
    path('org/my-documents/',                               MyDocumentsView.as_view()),
    path('org/my-documents/<int:pk>/upload/',               MyDocumentUploadView.as_view()),
    path('org/my-documents/<int:pk>/sign/',                 MyDocumentSignView.as_view()),
    # Training Courses
    path('org/courses/',                                    CourseListView.as_view()),
    path('org/courses/<int:pk>/',                           CourseDetailView.as_view()),
    path('org/courses/<int:pk>/modules/',                   CourseModuleListView.as_view()),
    path('org/courses/<int:pk>/enroll/',                    CourseEnrollView.as_view()),
    path('org/courses/<int:pk>/enrollments/',               CourseEnrollmentListView.as_view()),
    path('org/courses/<int:pk>/enrollments/<int:user_pk>/', CourseUnenrollView.as_view()),
    # Modules & Lessons
    path('org/modules/<int:pk>/',                           CourseModuleDetailView.as_view()),
    path('org/modules/<int:pk>/lessons/',                   ModuleLessonListView.as_view()),
    path('org/lessons/<int:pk>/',                           ModuleLessonDetailView.as_view()),
    path('org/lessons/<int:pk>/upload/',                    LessonFileUploadView.as_view()),
    path('org/lessons/<int:pk>/duplicate/',                 DuplicateLessonView.as_view()),
    path('org/modules/<int:pk>/reorder/',                   ReorderLessonsView.as_view()),
    # My Training (member)
    path('org/my-training/',                                MyTrainingView.as_view()),
    path('org/my-training/<int:enrollment_pk>/lessons/<int:lesson_pk>/', LessonCompleteView.as_view()),
    # Quiz questions (admin)
    path('org/lessons/<int:lesson_id>/questions/',          QuizQuestionListView.as_view()),
    path('org/questions/<int:pk>/',                         QuizQuestionDetailView.as_view()),
    # Lesson submit (member quiz / assignment)
    path('org/my-training/<int:enrollment_id>/lessons/<int:lesson_id>/submit/', LessonSubmitView.as_view()),
    # Events — summary before <pk> to avoid conflict
    path('org/events/',                                     EventListView.as_view()),
    path('org/events/<int:pk>/',                            EventDetailView.as_view()),
    path('org/events/<int:pk>/rsvp/',                       EventRSVPView.as_view()),
    path('org/events/<int:pk>/attendance/<int:user_pk>/',   EventAttendanceAdminView.as_view()),
    # Event type config + settings
    path('org/event-types/',                                EventTypeConfigListView.as_view()),
    path('org/event-types/<int:pk>/',                       EventTypeConfigDetailView.as_view()),
    path('org/event-settings/',                             EventSettingsView.as_view()),
    # Contributions — fixed paths before <pk>
    path('org/contributions/summary/',                      ContributionSummaryView.as_view()),
    path('org/contributions/insights/',                     ContributionInsightsView.as_view()),
    path('org/contributions/members/',                      ContributionMembersView.as_view()),
    path('org/contributions/bulk-review/',                  ContributionBulkReviewView.as_view()),
    path('org/contributions/admin-summary/',                ContributionAdminSummaryView.as_view()),
    path('org/contributions/overview/',                     ContributionOverviewView.as_view()),
    path('org/contributions/by-department/',                ContributionByDepartmentView.as_view()),
    path('org/contributions/export/',                       ContributionExportView.as_view()),
    path('org/contributions/',                              ContributionListView.as_view()),
    path('org/contributions/<int:pk>/',                     ContributionDetailView.as_view()),
    path('org/contributions/<int:pk>/review/',              ContributionReviewView.as_view()),
    # Check-ins
    path('org/checkins/',                                   CheckInListView.as_view()),
    path('org/checkins/<int:pk>/',                          CheckInDetailView.as_view()),
    path('org/checkins/<int:pk>/review/',                   CheckInReviewView.as_view()),
    # Dashboard
    path('org/dashboard/',                                  AdminDashboardView.as_view()),
    # Resources
    path('org/resources/',                                  ResourceListView.as_view()),
    path('org/resources/<int:pk>/',                         ResourceDetailView.as_view()),
    # Audit Log
    path('org/audit/',                                      AuditLogListView.as_view()),
    # Phase 7
    path('org/settings/',                                   OrgSettingsView.as_view()),
    path('org/analytics/',                                  AnalyticsView.as_view()),
    path('org/my-performance/',                             MemberPerformanceView.as_view()),
    # Phase 8
    path('org/recruitment/',                                RecruitmentListView.as_view()),
    path('org/recruitment/<int:pk>/review/',                RecruitmentReviewView.as_view()),
    # Standalone Forms
    path('org/forms/',                                      StandaloneFormListView.as_view()),
    path('org/forms/insights/',                             FormInsightsView.as_view()),
    path('org/forms/<int:pk>/',                             StandaloneFormDetailView.as_view()),
    path('org/forms/<int:pk>/fields/',                      StandaloneFormFieldListView.as_view()),
    path('org/form-fields/<int:pk>/',                       StandaloneFormFieldDetailView.as_view()),
    path('org/forms/<int:pk>/distribute/',                  FormDistributeView.as_view()),
    path('org/forms/<int:pk>/submit/',                      FormSubmitView.as_view()),
    path('org/forms/<int:pk>/responses/',                   FormResponsesView.as_view()),
    path('org/my-forms/',                                   MyFormsView.as_view()),
    # Extension Requests
    path('org/training/extension-requests/',                ExtensionRequestListView.as_view()),
    path('org/training/extension-requests/<int:pk>/review/', ExtensionRequestReviewView.as_view()),
    path('org/my-training/extension-request/',              ExtensionRequestSubmitView.as_view()),
    # Org Chat — Channels
    path('org/chat/channels/',                                   OrgChannelListView.as_view()),
    path('org/chat/channels/<int:pk>/',                          OrgChannelDetailView.as_view()),
    path('org/chat/channels/<int:pk>/members/',                  OrgChannelMembersView.as_view()),
    path('org/chat/channels/<int:pk>/messages/',                 OrgChannelMessageListView.as_view()),
    path('org/chat/channels/<int:pk>/messages/<int:mid>/',       OrgChannelMessageDetailView.as_view()),
    path('org/chat/channels/<int:pk>/messages/<int:mid>/pin/',   OrgChannelMessagePinView.as_view()),
    path('org/chat/channels/<int:pk>/messages/<int:mid>/react/', OrgChannelMessageReactView.as_view()),
    path('org/chat/channels/<int:pk>/polls/',                    OrgChannelPollListView.as_view()),
    path('org/chat/channels/<int:pk>/polls/<int:pid>/',          OrgChannelPollDetailView.as_view()),
    path('org/chat/channels/<int:pk>/polls/<int:pid>/vote/',     OrgChannelPollVoteView.as_view()),
    # Org Chat — DMs
    path('org/chat/dms/',                                        OrgDMConversationListView.as_view()),
    path('org/chat/dms/<int:user_id>/',                          OrgDMMessageListView.as_view()),
    path('org/chat/dms/<int:user_id>/<int:mid>/',                OrgDMMessageDetailView.as_view()),
]
