# Generated by Django 4.2.9 on 2026-06-19 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('access_granted', 'Access Granted'), ('access_revoked', 'Access Revoked'), ('role_changed', 'Role Changed'), ('agreement_posted', 'Agreement Posted'), ('checkin_due', 'Check-in Due'), ('contribution_approved', 'Contribution Approved'), ('recruitment_request', 'Recruitment Request'), ('application_reviewed', 'Application Reviewed')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
