# Generated by Django 4.2.9 on 2026-06-19 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org_portal', '0002_add_org_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='org_portal.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('required', 'Required'), ('policy', 'Policy'), ('form', 'Form'), ('certificate', 'Certificate')], default='required', max_length=20)),
                ('file', models.FileField(upload_to='doc_templates/')),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('requires_signature', models.BooleanField(default=False)),
                ('expiration_months', models.PositiveSmallIntegerField(default=0, help_text='0 = never expires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_doc_templates', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_templates', to='org_portal.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('orientation', 'Orientation'), ('welcome', 'Welcome Session'), ('training', 'Training'), ('webinar', 'Webinar'), ('checkin', 'Check-In'), ('meeting', 'Meeting')], default='meeting', max_length=20)),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=300)),
                ('virtual_link', models.CharField(blank=True, max_length=500)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_dt'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_onboardings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_templates', to='org_portal.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='training/thumbnails/')),
                ('is_mandatory', models.BooleanField(default=False)),
                ('pass_score', models.PositiveSmallIntegerField(default=70, help_text='Minimum score (0-100) to pass')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_courses', to='org_portal.department')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='orgmember',
            name='buddy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buddied_members', to='org_portal.orgmember'),
        ),
        migrations.AddField(
            model_name='orgmember',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='orgmember',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='orgmember',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='orgmember',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='org_portal.orgmember'),
        ),
        migrations.AddField(
            model_name='orgmember',
            name='profile_completion_pct',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orgmember',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='orgnotification',
            name='type',
            field=models.CharField(choices=[('access_granted', 'Access Granted'), ('access_revoked', 'Access Revoked'), ('role_changed', 'Role Changed'), ('department_assigned', 'Department Assigned'), ('onboarding_started', 'Onboarding Started'), ('task_assigned', 'Task Assigned'), ('task_overdue', 'Task Overdue'), ('document_approved', 'Document Approved'), ('document_rejected', 'Document Rejected'), ('agreement_posted', 'Agreement Posted'), ('training_assigned', 'Training Assigned'), ('event_scheduled', 'Event Scheduled'), ('checkin_due', 'Check-in Due'), ('contribution_approved', 'Contribution Approved'), ('recruitment_request', 'Recruitment Request'), ('application_reviewed', 'Application Reviewed')], max_length=50),
        ),
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='org_portal.trainingcourse')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrainingLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('lesson_type', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('quiz', 'Quiz'), ('assessment', 'Assessment'), ('external_link', 'External Link')], default='video', max_length=20)),
                ('content_url', models.CharField(blank=True, max_length=500)),
                ('content_file', models.FileField(blank=True, null=True, upload_to='training/lessons/')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='org_portal.trainingmodule')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrainingEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='enrolled', max_length=20)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='org_portal.trainingcourse')),
                ('enrolled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_enrollments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='TaskTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('task_type', models.CharField(choices=[('info', 'Information'), ('form', 'Form'), ('upload', 'Upload'), ('approval', 'Approval'), ('meeting', 'Meeting')], default='info', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('due_offset_days', models.PositiveIntegerField(default=0, help_text='Days after onboarding start date this task is due')),
                ('required', models.BooleanField(default=True)),
                ('approval_required', models.BooleanField(default=False)),
                ('assignee_type', models.CharField(choices=[('new_hire', 'New Hire'), ('manager', 'Manager'), ('buddy', 'Buddy'), ('hr', 'HR'), ('it', 'IT'), ('dept_admin', 'Department Admin')], default='new_hire', max_length=20)),
                ('dependencies', models.ManyToManyField(blank=True, related_name='dependents', to='org_portal.tasktemplateitem')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='org_portal.onboardingtemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TaskInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('task_type', models.CharField(default='info', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('blocked', 'Blocked')], default='not_started', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='org_task_attachments/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='org_portal.onboardinginstance')),
                ('template_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org_portal.tasktemplateitem')),
            ],
            options={
                'ordering': ['due_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('handbook', 'Employee Handbook'), ('guide', 'Guide'), ('faq', 'FAQ'), ('policy', 'Policy'), ('training_material', 'Training Material')], default='guide', max_length=30)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('external_url', models.CharField(blank=True, max_length=500)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.AddField(
            model_name='onboardinginstance',
            name='buddy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buddy_onboardings', to='org_portal.orgmember'),
        ),
        migrations.AddField(
            model_name='onboardinginstance',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_onboardings', to='org_portal.orgmember'),
        ),
        migrations.AddField(
            model_name='onboardinginstance',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='org_portal.onboardingtemplate'),
        ),
        migrations.AddField(
            model_name='onboardinginstance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_instances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MemberDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('file', models.FileField(blank=True, null=True, upload_to='org_documents/')),
                ('category', models.CharField(default='required', max_length=20)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('uploaded', 'Uploaded'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='assigned', max_length=20)),
                ('reviewer_note', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_documents', to='org_portal.documenttemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('contribution_type', models.CharField(choices=[('hours', 'Hours Worked'), ('task', 'Task Completed'), ('deliverable', 'Deliverable')], default='hours', max_length=20)),
                ('hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contributions', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='org_portal.orgmember')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('responses', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='org_portal.orgmember')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.AddField(
            model_name='orgmember',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='org_portal.department'),
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='org_portal.trainingenrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='org_portal.traininglesson')),
            ],
            options={
                'unique_together': {('enrollment', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsvp', models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('maybe', 'Maybe'), ('no_response', 'No Response')], default='no_response', max_length=20)),
                ('attended', models.BooleanField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='org_portal.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('export', 'Export'), ('approve', 'Approve')], max_length=20)),
                ('module', models.CharField(max_length=100)),
                ('record_id', models.IntegerField(blank=True, null=True)),
                ('record_repr', models.CharField(blank=True, max_length=300)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['module', 'action'], name='org_portal__module_7f7065_idx'), models.Index(fields=['created_at'], name='org_portal__created_4c06e2_idx'), models.Index(fields=['actor'], name='org_portal__actor_i_dd0e97_idx')],
            },
        ),
    ]
