# Generated by Django 4.2.9 on 2026-06-19 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org_portal', '0005_recruitmentrequest_orgagreement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('field_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('choice', 'Multiple Choice'), ('boolean', 'Yes / No'), ('date', 'Date'), ('number', 'Number')], default='text', max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='org_portal.taskinstance')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='orgnotification',
            name='type',
            field=models.CharField(choices=[('access_granted', 'Access Granted'), ('access_revoked', 'Access Revoked'), ('role_changed', 'Role Changed'), ('department_assigned', 'Department Assigned'), ('onboarding_started', 'Onboarding Started'), ('task_assigned', 'Task Assigned'), ('task_overdue', 'Task Overdue'), ('document_approved', 'Document Approved'), ('document_rejected', 'Document Rejected'), ('agreement_posted', 'Agreement Posted'), ('training_assigned', 'Training Assigned'), ('event_scheduled', 'Event Scheduled'), ('checkin_due', 'Check-in Due'), ('contribution_approved', 'Contribution Approved'), ('contribution_submitted', 'Contribution Submitted'), ('checkin_submitted', 'Check-in Submitted'), ('document_uploaded', 'Document Uploaded'), ('agreement_signed', 'Agreement Signed'), ('recruitment_request', 'Recruitment Request'), ('application_reviewed', 'Application Reviewed')], max_length=50),
        ),
        migrations.CreateModel(
            name='TemplateFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('field_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('choice', 'Multiple Choice'), ('boolean', 'Yes / No'), ('date', 'Date'), ('number', 'Number')], default='text', max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='org_portal.tasktemplateitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TaskFormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='org_portal.taskformfield')),
            ],
        ),
    ]
