# Generated by Django 4.2.9 on 2026-06-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_portal', '0006_form_builder'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstance',
            name='phase',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tasktemplateitem',
            name='phase',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
