# Generated by Django 4.2.9 on 2026-06-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_portal', '0007_task_phases'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstance',
            name='content_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='content_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='tasktemplateitem',
            name='content_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tasktemplateitem',
            name='content_file',
            field=models.FileField(blank=True, null=True, upload_to='task_content/'),
        ),
        migrations.AddField(
            model_name='tasktemplateitem',
            name='content_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
