# Generated by Django 4.2.9 on 2026-06-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_portal', '0009_task_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardinginstance',
            name='welcome_message',
            field=models.TextField(blank=True),
        ),
    ]
