# Generated by Django 4.2.9 on 2026-06-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_portal', '0010_onboarding_welcome_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardinginstance',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
