# Generated by Django 4.2.9 on 2026-06-20 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org_portal', '0011_onboarding_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingtemplate',
            name='assignable_by',
            field=models.CharField(blank=True, default='HR Admin, Managers', max_length=200),
        ),
        migrations.AddField(
            model_name='onboardingtemplate',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='onboardingtemplate',
            name='due_date_policy',
            field=models.CharField(blank=True, default='Relative to start date', max_length=100),
        ),
        migrations.AddField(
            model_name='onboardingtemplate',
            name='task_approval_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboardingtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='onboardingtemplate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onboardingtemplate',
            name='visible_to',
            field=models.CharField(blank=True, default='All Departments', max_length=200),
        ),
    ]
