# Generated by Django 4.2.9 on 2026-06-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_portal', '0012_template_category_settings_updated_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='approval_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='assignable_by',
            field=models.CharField(blank=True, default='HR Admin, Managers', max_length=200),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='auto_request_in_onboarding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='reminder_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='visible_to',
            field=models.CharField(blank=True, default='All Departments', max_length=200),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='doc_templates/'),
        ),
    ]
