# Generated by Django 4.2.9 on 2026-06-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_portal', '0013_documenttemplate_approval_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='category',
            field=models.CharField(blank=True, choices=[('compliance', 'Compliance'), ('technical', 'Technical'), ('soft_skills', 'Soft Skills'), ('leadership', 'Leadership'), ('onboarding', 'Onboarding'), ('health_safety', 'Health & Safety'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
