# Generated by Django 4.2.9 on 2026-06-20 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_portal', '0014_trainingcourse_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='training_auto_enroll_mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='training_certificate_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='training_default_pass_score',
            field=models.PositiveSmallIntegerField(default=70),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='training_reminder_days',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
