# Generated by Django 4.2.9 on 2026-06-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_portal', '0016_traininglesson_content_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_attendees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='target_audience',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
