# Generated by Django 4.2.9 on 2026-06-20 16:59

from django.db import migrations, models


def seed_event_types(apps, schema_editor):
    ETC = apps.get_model('org_portal', 'EventTypeConfig')
    defaults = [
        ('orientation', 'Orientation'),
        ('welcome',     'Welcome Session'),
        ('training',    'Training'),
        ('webinar',     'Webinar'),
        ('checkin',     'Check-in'),
        ('meeting',     'Meeting'),
    ]
    for slug, label in defaults:
        ETC.objects.get_or_create(slug=slug, defaults={'label': label, 'is_default': True, 'is_active': True})


class Migration(migrations.Migration):

    dependencies = [
        ('org_portal', '0017_event_target_audience_max_attendees'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_self_rsvp', models.BooleanField(default=True)),
                ('rsvp_deadline_hours', models.PositiveIntegerField(default=0)),
                ('default_duration_minutes', models.PositiveIntegerField(default=60)),
                ('send_reminders', models.BooleanField(default=True)),
                ('reminder_hours_before', models.PositiveIntegerField(default=24)),
                ('require_attendance_marking', models.BooleanField(default=False)),
                ('default_location', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.RunPython(seed_event_types, migrations.RunPython.noop),
    ]
