# Generated by Django 4.2.9 on 2026-06-21 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org_portal', '0020_department_is_active_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandaloneForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('show_results_to_members', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_forms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StandaloneFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('field_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('choice', 'Multiple Choice (single)'), ('multiselect', 'Multi-select'), ('boolean', 'Yes / No'), ('date', 'Date'), ('number', 'Number'), ('rating', 'Rating Scale'), ('file', 'File Upload')], default='text', max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('rating_max', models.PositiveIntegerField(default=5)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='org_portal.standaloneform')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FormDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('org', 'Whole Org'), ('department', 'Department'), ('members', 'Specific Members')], default='org', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org_portal.department')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='org_portal.standaloneform')),
                ('members', models.ManyToManyField(blank=True, related_name='form_distributions', to='org_portal.orgmember')),
            ],
        ),
        migrations.CreateModel(
            name='StandaloneFormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='form_responses/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='org_portal.standaloneformfield')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='org_portal.standaloneform')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_field_responses', to='org_portal.orgmember')),
            ],
            options={
                'unique_together': {('form', 'member', 'field')},
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='org_portal.standaloneform')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='org_portal.orgmember')),
            ],
            options={
                'unique_together': {('form', 'member')},
            },
        ),
    ]
