# Generated by Django 4.2.9 on 2026-06-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_portal', '0021_standaloneform_standaloneformfield_formdistribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standaloneform',
            name='form_type',
            field=models.CharField(choices=[('form', 'Form'), ('survey', 'Survey')], default='form', max_length=20),
        ),
        migrations.AlterField(
            model_name='orgnotification',
            name='type',
            field=models.CharField(choices=[('access_granted', 'Access Granted'), ('access_revoked', 'Access Revoked'), ('role_changed', 'Role Changed'), ('department_assigned', 'Department Assigned'), ('onboarding_started', 'Onboarding Started'), ('task_assigned', 'Task Assigned'), ('task_overdue', 'Task Overdue'), ('document_approved', 'Document Approved'), ('document_rejected', 'Document Rejected'), ('agreement_posted', 'Agreement Posted'), ('training_assigned', 'Training Assigned'), ('event_scheduled', 'Event Scheduled'), ('checkin_due', 'Check-in Due'), ('contribution_approved', 'Contribution Approved'), ('contribution_submitted', 'Contribution Submitted'), ('checkin_submitted', 'Check-in Submitted'), ('document_uploaded', 'Document Uploaded'), ('agreement_signed', 'Agreement Signed'), ('recruitment_request', 'Recruitment Request'), ('application_reviewed', 'Application Reviewed'), ('form_assigned', 'Form Assigned')], max_length=50),
        ),
    ]
