# Generated by Django 4.2.9 on 2026-06-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_portal', '0022_standaloneform_form_type_alter_orgnotification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstance',
            name='approval_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='content_file',
            field=models.FileField(blank=True, null=True, upload_to='org_task_content/'),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='required',
            field=models.BooleanField(default=True),
        ),
    ]
