# Generated by Django 4.2.9 on 2026-06-27 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_portal', '0034_event_recurrence_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='recurrence_end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='recurrence_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='series_id',
        ),
    ]
