# Generated by Django 4.2.9 on 2026-06-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_portal', '0036_org_chat_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgmember',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='org_member_pics/'),
        ),
    ]
