# Generated by Django 4.2.9 on 2026-07-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_portal', '0037_org_member_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgmember',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='org_members/pictures/'),
        ),
    ]
