# Generated by Django 4.2.9 on 2026-07-04 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_portal', '0038_add_profile_picture_to_orgmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalrole',
            name='can_approve_checkins',
        ),
        migrations.RemoveField(
            model_name='internalrole',
            name='can_upload_agreements',
        ),
    ]
