# Generated by Django 4.2.9 on 2026-06-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='theme_color',
            field=models.CharField(default='terracotta', max_length=30),
        ),
    ]
