# Generated by Django 4.2.9 on 2026-02-27 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('needs_revision', 'Needs Revision')], default='todo', max_length=20),
        ),
    ]
