# Generated by Django 4.2.9 on 2026-06-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_allow_null_student_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='background_experience',
            field=models.TextField(blank=True, help_text='Your background / experience level', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='headline',
            field=models.CharField(blank=True, help_text='One-line professional headline', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mentor_expectations',
            field=models.TextField(blank=True, help_text='What are you looking for in a mentor?', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mentorship_goals',
            field=models.TextField(blank=True, help_text='What are you hoping to achieve through mentorship?', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='pronouns',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
