# Generated by Django 4.2.9 on 2026-06-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='announcement',
            field=models.TextField(blank=True, help_text='Pinned announcement shown to all members'),
        ),
    ]
