# Generated by Django 4.2.9 on 2026-06-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_notification_notif_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceresource',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Mark as a downloadable template for members'),
        ),
    ]
