# Generated by Django 4.2.9 on 2026-06-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_workspaceresource_is_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('step_submitted', 'Step Submitted'), ('step_reviewed', 'Step Reviewed'), ('app_status', 'Application Status Changed'), ('ws_request', 'Workspace Join Request'), ('ws_approved', 'Workspace Request Approved'), ('ws_rejected', 'Workspace Request Rejected'), ('new_message', 'New Message'), ('feed_post', 'New Feed Post'), ('session', 'Session Booked'), ('deadline', 'Deadline Reminder')], max_length=30),
        ),
    ]
