# Generated by Django 4.2.9 on 2026-06-10 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_message_attachment_alter_message_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='auto_accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspace',
            name='category',
            field=models.CharField(blank=True, choices=[('study_abroad', 'Study Abroad'), ('language_prep', 'Language Prep'), ('scholarship', 'Scholarship'), ('visa', 'Visa'), ('career', 'Career'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='workspace',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='workspace_covers/'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='goal',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='workspace',
            name='icon_emoji',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='workspace',
            name='invite_token',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='workspace',
            name='language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='workspace',
            name='max_members',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='office_hours',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='workspace',
            name='pinned_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='pinned_url_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='workspace',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('secret', 'Secret')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='workspace',
            name='related_workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_to', to='core.workspace'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='target_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workspace',
            name='target_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='target_degree',
            field=models.CharField(blank=True, choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD'), ('exchange', 'Exchange'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='workspace',
            name='welcome_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='workspace_status',
            field=models.CharField(choices=[('active', 'Active'), ('winding_down', 'Winding Down'), ('archived', 'Archived')], default='active', max_length=15),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='announcement',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
