# Generated by Django 4.2.9 on 2026-06-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_workspace_auto_accept_workspace_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='countries_expertise',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='current_company',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='current_role',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='education',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='headline',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='languages',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='mentoring_areas',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='mentoring_style',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='pronouns',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='what_i_offer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='years_experience',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
