# Generated by Django 4.2.9 on 2026-06-10 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_mentorprofile_city_mentorprofile_countries_expertise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofile',
            name='pronouns',
        ),
    ]
