# Generated by Django 4.2.9 on 2026-06-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_workspace_accent_color_workspace_logo_workspace_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='allow_self_unenroll',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='completion_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspace',
            name='course_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='course_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='enable_chat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='enable_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspace',
            name='enable_resources',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='enable_tasks',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='enrollment_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='estimated_duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workspace',
            name='grade_display',
            field=models.CharField(choices=[('points', 'Points'), ('percentage', 'Percentage'), ('letter', 'Letter Grade')], default='points', max_length=15),
        ),
        migrations.AddField(
            model_name='workspace',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=15),
        ),
        migrations.AddField(
            model_name='workspace',
            name='min_completion_pct',
            field=models.PositiveIntegerField(default=80),
        ),
        migrations.AddField(
            model_name='workspace',
            name='syllabus_url',
            field=models.URLField(blank=True),
        ),
    ]
