# Generated by Django 4.2.9 on 2026-06-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_workspace_allow_self_unenroll_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Hidden from student view when True'),
        ),
        migrations.AddField(
            model_name='workspaceresource',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Hidden from students when True'),
        ),
    ]
