# Generated by Django 4.2.9 on 2026-06-11 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_add_is_hidden_to_resource_and_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('step_submitted', 'Step Submitted'), ('step_reviewed', 'Step Reviewed'), ('app_status', 'Application Status Changed'), ('ws_request', 'Workspace Join Request'), ('ws_approved', 'Workspace Request Approved'), ('ws_rejected', 'Workspace Request Rejected'), ('new_message', 'New Message'), ('feed_post', 'New Feed Post'), ('session', 'Session Booked'), ('deadline', 'Deadline Reminder'), ('task_reminder', 'Personal Task Reminder')], max_length=30),
        ),
        migrations.CreateModel(
            name='PersonalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('reminder_offset', models.IntegerField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_tasks', to='core.studentprofile')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
