# Generated by Django 4.2.9 on 2026-06-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_notification_notif_type_personaltask'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='event_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='event_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='event_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='event_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='event_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
