# Generated by Django 4.2.9 on 2026-06-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_workspaceevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='goal',
            field=models.TextField(blank=True),
        ),
    ]
