# Generated by Django 4.2.9 on 2026-06-12 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_workspace_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.workspace'),
        ),
    ]
