# Generated by Django 4.2.9 on 2026-06-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_post_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceresource',
            name='category',
            field=models.CharField(blank=True, choices=[('documents', 'Documents'), ('presentations', 'Presentations'), ('guides', 'Guides'), ('links', 'Links'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='workspaceresource',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
