# Generated by Django 4.2.9 on 2026-06-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_workspaceresource_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemembership',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor')], default='viewer', max_length=10),
        ),
    ]
