# Generated by Django 4.2.9 on 2026-06-13 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0036_workspacetask_workspacetaskdeliverable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacetask',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspacetasksubmission',
            name='due_date_override',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspacetasksubmission',
            name='reminder_24h_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspacetasksubmission',
            name='reminder_48h_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WorkspaceTaskMentorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_mentor_notes', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_notes', to='core.workspacetasksubmission')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceTaskPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='core.workspacetask')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='core.workspacetask')),
            ],
            options={
                'unique_together': {('task', 'required_task')},
            },
        ),
    ]
