# Generated by Django 4.2.9 on 2026-06-13 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_task_status_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacetask',
            name='assigned_members',
            field=models.ManyToManyField(blank=True, help_text='If empty, assigned to all workspace members; if set, only these students.', related_name='selective_tasks', to='core.studentprofile'),
        ),
        migrations.AddField(
            model_name='workspacetask',
            name='available_from',
            field=models.DateTimeField(blank=True, help_text='Task becomes visible to students from this datetime', null=True),
        ),
        migrations.AddField(
            model_name='workspacetask',
            name='available_until',
            field=models.DateTimeField(blank=True, help_text='Task auto-hides after this datetime', null=True),
        ),
        migrations.CreateModel(
            name='WorkspaceTaskSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, default='gray', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_sections', to='core.workspace')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceTaskRubricCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('max_points', models.PositiveSmallIntegerField(default=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_criteria', to='core.workspacetask')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='workspacetask',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.workspacetasksection'),
        ),
        migrations.CreateModel(
            name='WorkspaceTaskRubricScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('feedback', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.workspacetaskrubriccriteria')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_scores', to='core.workspacetasksubmission')),
            ],
            options={
                'unique_together': {('submission', 'criteria')},
            },
        ),
    ]
