# Generated by Django 4.2.9 on 2026-06-13 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0039_features_11_15'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacetask',
            name='grace_period_hours',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workspacetask',
            name='late_policy',
            field=models.CharField(choices=[('accept', 'Accept Late'), ('reject', 'Reject Late'), ('penalty', 'Accept with Penalty Flag')], default='accept', max_length=10),
        ),
        migrations.AddField(
            model_name='workspacetask',
            name='peer_review_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workspacetask',
            name='peer_review_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspacetasksubmission',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspacetasksubmission',
            name='late_override',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('step_submitted', 'Step Submitted'), ('step_reviewed', 'Step Reviewed'), ('app_status', 'Application Status Changed'), ('ws_request', 'Workspace Join Request'), ('ws_approved', 'Workspace Request Approved'), ('ws_rejected', 'Workspace Request Rejected'), ('new_message', 'New Message'), ('feed_post', 'New Feed Post'), ('session', 'Session Booked'), ('deadline', 'Deadline Reminder'), ('task_reminder', 'Personal Task Reminder'), ('mention', 'Mentioned in Comment'), ('peer_review_assigned', 'Peer Review Assigned')], max_length=30),
        ),
        migrations.CreateModel(
            name='WorkspaceTaskSelfAssessQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_assess_questions', to='core.workspacetask')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceTaskPeerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('submitted', 'Submitted')], default='assigned', max_length=10)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewee_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews', to='core.workspacetasksubmission')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews_given', to='core.studentprofile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews', to='core.workspacetask')),
            ],
            options={
                'ordering': ['assigned_at'],
                'unique_together': {('task', 'reviewer', 'reviewee_submission')},
            },
        ),
        migrations.CreateModel(
            name='DocumentInlineComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveSmallIntegerField(default=1)),
                ('x_pct', models.FloatField(default=50.0)),
                ('y_pct', models.FloatField(default=50.0)),
                ('body', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_inline_comments', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inline_comments', to='core.workspacetaskdocument')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.documentinlinecomment')),
            ],
            options={
                'ordering': ['page_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceTaskSelfAssessResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.workspacetaskselfassessquestion')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_assess_responses', to='core.workspacetasksubmission')),
            ],
            options={
                'unique_together': {('submission', 'question')},
            },
        ),
        migrations.CreateModel(
            name='WorkspaceTaskPeerReviewScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('feedback', models.TextField(blank=True)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_scores', to='core.workspacetaskrubriccriteria')),
                ('peer_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.workspacetaskpeerreview')),
            ],
            options={
                'unique_together': {('peer_review', 'criteria')},
            },
        ),
    ]
