# Generated by Django 4.2.9 on 2026-06-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_features_16_20'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='domain',
            field=models.CharField(blank=True, choices=[('stem', 'STEM'), ('business', 'Business & Economics'), ('humanities', 'Humanities'), ('medicine', 'Medicine & Health Sciences'), ('law', 'Law'), ('arts', 'Arts & Design'), ('social_sciences', 'Social Sciences'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='own_degree',
            field=models.CharField(blank=True, help_text='e.g. BSc, MSc, PhD, MBA', max_length=60),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='own_field_of_study',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='own_graduation_year',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='own_university',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='preferred_student_level',
            field=models.CharField(blank=True, choices=[('undergraduate', 'Undergraduate'), ('masters', "Master's"), ('phd', 'PhD'), ('any', 'Any level')], max_length=20),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='timezone',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
