# Generated by Django 4.2.9 on 2026-06-14 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_mentor_profile_new_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='application',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='step',
        ),
        migrations.RemoveField(
            model_name='document',
            name='application',
        ),
        migrations.RemoveField(
            model_name='document',
            name='step',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='step',
            name='application',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Step',
        ),
    ]
