# Generated by Django 4.2.9 on 2026-06-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_application_step_comment_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='target_country',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='target_degree',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='career_stage',
            field=models.CharField(blank=True, choices=[('high_school', 'High school student'), ('undergraduate', 'Undergraduate student'), ('postgraduate', 'Postgraduate student'), ('early_career', 'Early career (0–3 years)'), ('mid_career', 'Mid career (3–10 years)'), ('career_changer', 'Career changer'), ('other', 'Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='hobbies',
            field=models.TextField(blank=True, help_text='Hobbies and things you enjoy outside of work/study', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='interests',
            field=models.TextField(blank=True, help_text='Areas of interest (comma-separated or free text)', null=True),
        ),
    ]
