# Generated by Django 4.2.9 on 2026-06-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_remove_workspace_cover_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('step_submitted', 'Step Submitted'), ('step_reviewed', 'Step Reviewed'), ('app_status', 'Application Status Changed'), ('ws_request', 'Workspace Join Request'), ('ws_approved', 'Workspace Request Approved'), ('ws_rejected', 'Workspace Request Rejected'), ('ws_invite', 'Workspace Invitation'), ('new_message', 'New Message'), ('feed_post', 'New Feed Post'), ('session', 'Session Booked'), ('deadline', 'Deadline Reminder'), ('task_reminder', 'Personal Task Reminder'), ('mention', 'Mentioned in Comment'), ('peer_review_assigned', 'Peer Review Assigned')], max_length=30),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='category',
            field=models.CharField(blank=True, choices=[('career_coaching', 'Career Coaching'), ('skill_development', 'Skill Development'), ('academic', 'Academic Support'), ('interview_prep', 'Interview Prep'), ('project', 'Project-Based'), ('personal_growth', 'Personal Growth'), ('networking', 'Networking'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='workspacemembership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('invited', 'Invited'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
