# Generated by Django 4.2.9 on 2026-06-15 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_workspace_membership_invited_status_and_ws_invite_notif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspacemembership',
            name='role',
        ),
    ]
