# Generated by Django 4.2.9 on 2026-06-17 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0047_alter_notification_notif_type_workspacementorguest'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active')], default='invited', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_workspaces', to='core.mentorprofile')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_mentors', to='core.workspace')),
            ],
            options={
                'verbose_name': 'Workspace Mentor',
                'verbose_name_plural': 'Workspace Mentors',
                'unique_together': {('workspace', 'mentor')},
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('step_submitted', 'Step Submitted'), ('step_reviewed', 'Step Reviewed'), ('app_status', 'Application Status Changed'), ('ws_request', 'Workspace Join Request'), ('ws_approved', 'Workspace Request Approved'), ('ws_rejected', 'Workspace Request Rejected'), ('ws_invite', 'Workspace Invitation'), ('mentor_invite', 'Workspace Mentor Invite'), ('new_message', 'New Message'), ('feed_post', 'New Feed Post'), ('session', 'Session Booked'), ('deadline', 'Deadline Reminder'), ('task_reminder', 'Personal Task Reminder'), ('mention', 'Mentioned in Comment'), ('peer_review_assigned', 'Peer Review Assigned')], max_length=30),
        ),
        migrations.DeleteModel(
            name='WorkspaceMentorGuest',
        ),
    ]
