# Generated by Django 4.2.9 on 2026-06-18 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_workspacementor_alter_notification_notif_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='availability_info',
            field=models.TextField(blank=True, default='', help_text='Hours/week, time zone, preferred days'),
        ),
        migrations.CreateModel(
            name='WorkspaceOnboardingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_questions', to='core.workspace')),
            ],
            options={
                'verbose_name': 'Workspace Onboarding Question',
                'verbose_name_plural': 'Workspace Onboarding Questions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceOnboardingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.workspaceonboardingquestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ws_onboarding_answers', to='core.studentprofile')),
            ],
            options={
                'verbose_name': 'Workspace Onboarding Answer',
                'verbose_name_plural': 'Workspace Onboarding Answers',
                'unique_together': {('question', 'student')},
            },
        ),
    ]
