# Generated by Django 4.2.9 on 2026-06-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_theme_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='font_style',
            field=models.CharField(default='lato', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='theme_color',
            field=models.CharField(default='aubergine', max_length=30),
        ),
    ]
